# -*- coding: utf-8 -*-
from . import res_company
from . import microfinance_profession
from . import microfinance_repayment_frequency
from . import microfinance_loan_product
from . import microfinance_scoring
from . import microfinance_provision_rule
from . import microfinance_loan
from . import microfinance_loan_guarantee
from . import microfinance_loan_reschedule_history
from . import microfinance_loan_installment
from . import microfinance_loan_payment
from . import microfinance_collection_visit
from . import microfinance_dashboard
from . import microfinance_client_representative
from . import microfinance_client_blacklist
from . import microfinance_client_category
from . import microfinance_client_group_member
from . import microfinance_bailleur_fonds
from . import microfinance_fond_credit
from . import microfinance_fond_contribution
from . import microfinance_caisse_fiche_journee
from . import res_partner
