{
    'name': 'TRESORERIE',
    'version': '17.0.1.0.1',
    'summary': 'Rapport journalier des totaux débit/crédit',
    'category': 'Accounting',
    'author': 'Sysadptpro',
    'depends': ['account', 'hr_expense', 'web', 'point_of_sale', 'mail'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/advance_payment_sequence.xml',
        'data/menu_app_rename.xml',
        'report/paid_totals_report.xml',
        'views/paid_totals_views.xml',
        'views/paid_totals_views_mobile.xml',
        'views/res_config_settings_views.xml',
        'views/treasury_analysis_report_views.xml',
        'views/journal_libel.xml',
        'views/advance_payment_views.xml',
        'views/invoice_date_read_only.xml',
        'data/cron_account_daily_balance.xml',

    ],
    'assets': {
        'web.assets_backend': [
            'custom_paid_totals/static/src/scss/icon.scss',
            'custom_paid_totals/static/src/scss/daily_balance_summary_grid.scss',
            'custom_paid_totals/static/lib/apexcharts/apexcharts.min.js',
            'custom_paid_totals/static/src/js/daily_balance_dashboard.js',
            'custom_paid_totals/static/src/js/treasury_analysis_dashboard.js',
            'custom_paid_totals/static/src/xml/daily_balance_dashboard.xml',
            'custom_paid_totals/static/src/xml/treasury_analysis_dashboard.xml',
            'custom_paid_totals/static/src/scss/daily_balance_dashboard.scss',
            'custom_paid_totals/static/src/scss/treasury_analysis_dashboard.scss',
        ],
    },
    'installable': True,
    'application': True,
}
