# -*- coding: utf-8 -*-
{
    'name': 'Microfinance Loan Management',
    'version': '17.0.1.0.0',
    'summary': 'Gestion des crédits clients pour institutions de microfinance',
    'description': 'Produits de crédit, demandes, approbations, échéanciers, remboursements, pénalités, recouvrement et risque.',
    'category': 'Accounting/Finance',
    'author': 'SysAdaptPro',
    'website': 'https://sysadaptpro.com',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'account', 'contacts', 'hr', 'calendar', 'base_accounting_kit'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/cron.xml',
        'data/provision_rules_data.xml',
        'data/provision_server_action.xml',
        'report/microfinance_loan_disbursement_receipt.xml',
        'views/microfinance_loan_product_views.xml',
        'views/microfinance_provision_rule_views.xml',
        'views/microfinance_loan_views.xml',
        'views/microfinance_scoring_views.xml',
        'views/microfinance_loan_installment_views.xml',
        'views/microfinance_loan_payment_views.xml',
        'views/microfinance_collection_visit_views.xml',
        'wizard/microfinance_loan_payment_wizard_views.xml',
        'wizard/microfinance_loan_reschedule_wizard_views.xml',
        'wizard/microfinance_loan_writeoff_wizard_views.xml',
        'views/microfinance_dashboard_views.xml',
        'views/microfinance_menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'microfinance_loan_management/static/lib/apexcharts/apexcharts.min.js',
            'microfinance_loan_management/static/src/js/microfinance_loan_dashboard.js',
            'microfinance_loan_management/static/src/xml/microfinance_loan_dashboard.xml',
            'microfinance_loan_management/static/src/scss/microfinance_loan_dashboard.scss',
        ],
    },
    'application': True,
    'installable': True,
}
